#ifndef MESSAGETYPES_H
#define MESSAGETYPES_H

#define SPREAD_NAME "4803"
#define GROUP_NAME "SERVER_GROUP"
#define MAX_NO_SERVERS 3

#define MTYPE_HELLO 333
#define MTYPE_QUIT 666
#define MTYPE_MASTER_VOTE 123
#define MTYPE_ACKNOWLEDGE 111
#define MTYPE_QUIT 433

#endif // MESSAGETYPES_H
